server {
  listen 8080;
  server_name localhost;
  root www/localhost;
  index index.html;
}

server {
  listen 8080;
  server_name webserv.com;
  root www/webserv;
  index index.html;
}

server {
  listen 8081;
  server_name localhost;
  root www/port8081;
  index index.html;
}
