server {
  listen 8080;
  server_name localhost;
  root www/handlers;

  location / {
    autoindex off;
    index index.html;
  }

  location /files {
    autoindex on;
  }

  location /upload {
    allowed_methods POST DELETE;
  }

  location /cgi-bin {
    cgi_ext .php .py;
  }
}
