server {
  listen 8080;
  server_name localhost;
  
  # Firewall: Límite estricto de 10 bytes de payload
  client_max_body_size 10;

  location / {
    autoindex on;
  }

  location /readonly {
    allowed_methods GET;
  }
}
