server {
  listen 8080;
  server_name localhost;
  root www/routing;

  error_page 404 /custom_404.html;
  error_page 500 /custom_50x.html;

  location / {
    autoindex on;
  }

  location /old-site {
    redirect /new-site;
  }
}
